### PR TITLE
Removed outdated promise libraries which had security vulnerabilities

### PR DESCRIPTION
**Pull request by sax1johno**

### CODE REVIEW

**Comment by natcl** [comment]
Hello thanks for your pull request.
I just merged it.  I saw however that you published a new package on npm, to avoid confusion could you remove it so I can update mine ?

Thanks.

**Comment by sax1johno** [comment]
Yep - can do.  Thank you

**Comment by sax1johno** [comment]
FYI - it's now removed.

**Comment by natcl** [comment]
Thanks and thanks for the fixes !

Le ven. 3 janv. 2020, à 16 h 33, sax1johno <notifications@github.com> a
écrit :

**Pull request merged**
